#Ansible playbook for Warby Parker Sr. Infrastructure Engineer homework assignment.
#Authored by Martin Beauchamp, Copyright 2015

# This playbook implements the required steps to setup the homework test environment
# as specified here: https://github.com/ChairmanTubeAmp/WPH/blob/master/InfrastructureEngineer.md

---
- hosts: all

  vars:
    timezone: America/New_York
    
  tasks:

    # Set timezone to zone defined in timezone variable
  - name: Check current timezone
    shell: awk -F\" '{ print $2}' /etc/sysconfig/clock
    register: current_zone
    changed_when: False

  - name: Set timezone
    file: src=/usr/share/zoneinfo/{{ timezone }}  dest=/etc/localtime state=link force=yes
    when: current_zone.stdout != '{{ timezone }}'

  - name: Set CentOS clock
    command: echo 'ZONE="America/New_York"' > /etc/sysconfig/clock
    when: current_zone.stdout != '{{ timezone }}'

    # Start ntpd and enable it
  - service: name=ntpd state=started enabled=yes

#    # We get an out of date VM from Vagrant and so we must update the kernel and system packages
#  - name: Kernel package updates
#    action: yum name=kernel* state=latest
#    # If there are any updates, we register the variable and see if it changes in the Reboot and Wait tasks.
#    register: kernelupdate
    
#  - name: System package updates
#    action: yum name=* state=latest
      
#  - name: Reboot
#    command: shutdown -r now "Ansible kernel updates triggered a reboot."
#    async: 0
#    poll: 0
#    ignore_errors: true
#    when: kernelupdate.changed

#  - name: Wait for host to come back up
#    #This wait_for doesn't actually test SSH with Vagrant because of the port changes, but it makes the Playbook work
#    local_action: wait_for host={{ inventory_hostname }} delay=30 timeout=300 state=started
#    sudo: false
#    when: kernelupdate.changed
    
#- hosts: front

#  tasks:

#  # Install the required application packages
#  - name: Install Nginx and Memcached
#    yum: pkg={{ item }} state=present
#    with_items:
#      - epel-release
#      - nginx
#      - memcached
#      - emacs

- hosts: app

  tasks:

#  # Install the required application packages
#  - name: Install Apache and MySQL
#    yum: pkg={{ item }} state=present
#    with_items:
#      - httpd
#      - php
#      - mysql-server
#      - emacs

  #Copy the WPH files to the app server
  - name: Set ownership and modes on the Apache DocuemntRoot directory
    file: path=/var/www/html owner=apache group=apache mode=0770

  - name: Copy WPH PHP file to the app server
    copy: src={{ vagrantfile_basepath }}/workingdirectory/test.php dest=/var/www/html/test.php owner=apache group=apache mode=0660

  - name: Copy WPH SQL file to the app server
    copy: src={{ vagrantfile_basepath }}/workingdirectory/test.sql dest=/var/lib/mysql owner=mysql group=mysql mode=0640

    