# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
   # Set a base path
   basepath = "/Users/martinbeauchamp/Downloads/WarbyParkerHomework/"

   # Define box given by WP
   config.vm.box = "#{basepath}centos-65-x64-virtualbox-nocm.box"

   #Don't upgrade boxes automatically
   config.vm.box_check_update = false

#   # Display the VirtualBox GUI when booting the machine
#   config.vm.provider "virtualbox" do |vb|
#   vb.gui = true
#   end

   #Common VM attributes
   config.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)'
   config.vm.synced_folder ".", "/vagrant", :disabled => true
   
     #"front" specific VM attributes
     config.vm.define  :front do |front|
       front.vm.hostname = 'front'
       front.vm.network "private_network", ip: "10.1.1.10"
       front.vm.provider "virtualbox" do |vb|
         vb.memory = "2048"
       end
       
       #Update OS and all userland software
       front.vm.provision "shell", inline: <<-SHELL
         sudo yum -y update
         SHELL

       #Ansible-based provisioning
#       front.vm.provision :ansible do |ansible|
#       ansible.playbook = "#{basepath}/workingdirectory/vagrant/provisioning/front-playbook.yml"
#         ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
#         # Disable default limit (required with Vagrant 1.5+)
#         ansible.limit = 'all'
#       end
     end
     
#     #"app" specific VM attributes
     config.vm.define :app do |app|
       app.vm.hostname = 'app'
       app.vm.network "private_network", ip: "10.1.1.20"
       app.vm.provider "virtualbox" do |vb|
         vb.memory = "4096"
       end
     
       #Update OS and all userland software
       app.vm.provision "shell", inline: <<-SHELL
         sudo yum -y update
         SHELL

       #Ansible-based provisioning
 #      app.vm.provision :ansible do |ansible|
 #        ansible.playbook = "#{basepath}/workingdirectory/vagrant/provisioning/app-playbook.yml"
 #        ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
 #        # Disable default limit (required with Vagrant 1.5+)
 #        ansible.limit = 'all'
 #      end
#     end
end
end
