# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant config file for Warby Parker Sr. Infrastructure Engineer homework assignment.
#Authored by Martin Beauchamp, Copyright 2015

Vagrant.configure(2) do |config|
  
   # Set a base path
   basepath = "/Users/martinbeauchamp/Downloads/WarbyParkerHomework/"

   # Set IP addresses for hosts: front and app
   front_ip = "10.10.10.10"
   app_ip   = "10.10.10.20"

   # Set port for app server to listen on
   app_port = "8080"

   # Set yum updates to True or False
   yumupdate = "False"
   
   # Define Vagrant box given by WP
   config.vm.box = "#{basepath}centos-65-x64-virtualbox-nocm.box"

   #Don't upgrade boxes automatically
   config.vm.box_check_update = false

#   # Display the VirtualBox GUI when booting the machine
#   config.vm.provider "virtualbox" do |vb|
#   vb.gui = true
#   end

   #Common VM attributes
   #Each VM has a public network which uses a bridge device
   config.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)'

   #Disable shared folders between VM instances and the host - not needed, and this causes problems when you upgrade the kernel
   config.vm.synced_folder ".", "/vagrant", :disabled => true

   #"front" specific VM attributes
     config.vm.define "front" do |front|

       #HOSTNAME
       front.vm.hostname = 'front'

       #PRIVATE NETWORK
       front.vm.network "private_network", ip: "#{front_ip}"

       #RAM & CPUs
       front.vm.provider "virtualbox" do |vb|
         vb.memory = "2048"
         vb.cpus = 2
       end
       
       #Ansible-based provisioning
       front.vm.provision "ansible" do |ansible|
       ansible.playbook = "#{basepath}/workingdirectory/vagrant/provisioning/wph-playbook.yml"
       ansible.sudo = true
       ansible.extra_vars = { ansible_ssh_user:      "vagrant",
                              vagrantfile_front_ip:  "#{front_ip}",
                              vagrantfile_app_ip:    "#{app_ip}",
                              vagrantfile_app_port:  "#{app_port}",
                              vagrantfile_basepath:  "#{basepath}",
                              vagrantfile_yumupdate: "#{yumupdate}",
                            }
       # Disable default limit (required with Vagrant 1.5+)
       ansible.limit = 'front'
       end
     end
     
     #"app" specific VM attributes
     config.vm.define "app" do |app|

       #HOSTNAME
       app.vm.hostname = 'app'

       #PRIVATE NETWORK
       app.vm.network "private_network", ip: "#{app_ip}"

       #RAM & CPUs
       app.vm.provider "virtualbox" do |vb|
         vb.memory = "4096"
         vb.cpus = 2
       end

       #Ansible-based provisioning
       app.vm.provision "ansible" do |ansible|
         ansible.playbook = "#{basepath}/workingdirectory/vagrant/provisioning/wph-playbook.yml"
         ansible.sudo = true
         ansible.extra_vars = { ansible_ssh_user:      "vagrant",
                                vagrantfile_front_ip:  "#{front_ip}",
                                vagrantfile_app_ip:    "#{app_ip}",
                                vagrantfile_app_port:  "#{app_port}",
                                vagrantfile_basepath:  "#{basepath}",
                                vagrantfile_yumupdate: "#{yumupdate}",
                              }
         # Disable default limit (required with Vagrant 1.5+)
         ansible.limit = 'app'
       end
     end
end
